export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const LANDING = "LANDING"
export const HOME = "HOME"
export const VENDORDETAIL = "VENDOR DETAIL"
export const FOODDETAIL = "FOOD DETAIL"